---
name: 345SecurityMQTT
version: 0.3.0
init: false
slug: 345securitymqtt
description: 345SecurityMQTT with Auto Discovery support. It listens for events from
  345MHz security sensors and sends messages via MQTT.
url: https://github.com/kdeyev/345SecurityMQTT
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: application
boot: auto
services:
- mqtt:need
usb: true
udev: true
options:
  autodiscovery: true
  device_id: 0
  frequency: 345000000
  gain: 700
  sample_rate: 1000000
  mqtt_host: localhost
  mqtt_port: 1883
  mqtt_username: mqtt
  mqtt_password: mqtt
schema:
  autodiscovery: bool
  device_id: int
  frequency: int
  gain: int
  sample_rate: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
